CREATE TABLE SAMPLE_BOOKS (
    BOOK_NO     NUMBER(6,0) PRIMARY KEY,
    BOOK_TITLE  VARCHAR2(500) NOT NULL,
    BOOK_WRITE VARCHAR2(200) NOT NULL,
    BOOK_GENRE VARCHAR2(200) NOT NULL,
    BOOK_PUBLISHER VARCHAR2(200) NOT NULL,
    BOOK_PRICE NUMBER(7,0) DEFAULT 0,
    BOOK_DISCOUNT_PRICE NUMBER(7,0) NOT NULL,
    BOOK_REGISTERED_DATE DATE

);

CREATE SEQUENCE SAMPLE_BOOK_SEQ START WITH 10000;

INSERT INTO SAMPLE_BOOKS(
    BOOK_NO, BOOK_TITLE, BOOK_WRITE,BOOK_GENRE, BOOK_PUBLISHER, BOOK_PRICE, BOOK_DISCOUNT_PRICE, BOOK_REGISTERED_DATE
)
VALUES
(SAMPLE_BOOK_SEQ.NEXTVAL, '자바의정석', '남궁성','IT','도우출판사','30000',27000,SYSDATE);

SELECT * FROM SAMPLE_BOOKS;

SELECT * FROM sample_books WHERE book_genre LIKE '%1%';
SELECT * FROM SAMPLE_BOOKS WHERE BOOK_TITLE LIKE '%자바%' ORDER BY BOOK_NO DESC;

SELECT * FROM SAMPLE_BOOKS ORDER BY BOOK_NO DESC;

SELECT * FROM sample_books WHERE BOOK_NO = 10006;
SELECT * FROM sample_books WHERE BOOK_PRICE BETWEEN 1 AND 100000;

UPDATE sample_books SET book_title = '1', book_write = '1', book_genre = '1', book_publisher = '1', book_price = 0 WHERE BOOK_NO = '10004';
DELETE FROM sample_books WHERE BOOK_NO = '10003';

CREATE TABLE SAMPLE_BOOK_USERS (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    USER_PASSWORD VARCHAR2(50) NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(256) NOT NULL,
    USER_POINT NUMBER(10,0),
    USER_REGISTERED_DATE DATE
);

CREATE TABLE SAMPLE_BOOK_ORDERS(
    ORDER_NO NUMBER(6,0) PRIMARY KEY,
    USER_ID VARCHAR2(50) REFERENCES SAMPLE_BOOK_USERS (USER_ID),
    BOOK_NO NUMBER(6, 0) REFERENCES SAMPLE_BOOKS (BOOK_NO),
    ORDER_PRICE NUMBER(7,0),
    ORDER_AMOUNT NUMBER(3,0),
    ORDER_REGISTERED_DATE DATE
);

create SEQUENCE sample_order_Seq start with 50000;

INSERT INTO SAMPLE_BOOK_USERS
(USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL, USER_POINT, USER_REGISTERED_DATE)
VALUES
('HONG', 'ZXCV1234','홍길동','123@gmail.com', 1000, sysdate);
select * from sample_book_users;
insert into sample_book_orders
(order_no, user_id, book_no, order_price, order_amount, order_registered_date)
values
(sample_order_seq.nextval, 'HONG',10010,32000,2,SYSDATE);
